var SAW_QUESTIONS = [
    { q: { en: "Default SSH port number?", pl: "Domyślny numer portu SSH?", klingon: "SSH QaD mI' yIngu'?" }, a: "22" },
    { q: { en: "Default HTTP port number?", pl: "Domyślny numer portu HTTP?", klingon: "HTTP meb port mI' yIjatlh!" }, a: "80" },
    { q: { en: "Default HTTPS port number?", pl: "Domyślny numer portu HTTPS?", klingon: "HTTPS bach'egh port mI'?" }, a: "443" },
    { q: { en: "Default DNS port number?", pl: "Domyślny numer portu DNS?", klingon: "DNS pong-SIch port mI'?" }, a: "53" },
    { q: { en: "Default FTP data port?", pl: "Domyślny port danych FTP?", klingon: "FTP Doch-tlhap port mI'?" }, a: "20" },
    { q: { en: "Default FTP control port?", pl: "Domyślny port kontrolny FTP?", klingon: "FTP che' port mI'?" }, a: "21" },
    { q: { en: "Default SMTP port number?", pl: "Domyślny numer portu SMTP?", klingon: "SMTP QIn-lab port mI'?" }, a: "25" },
    { q: { en: "Default MySQL port number?", pl: "Domyślny numer portu MySQL?", klingon: "MySQL Soj-tev port mI'?" }, a: "3306" },
    { q: { en: "Default PostgreSQL port number?", pl: "Domyślny numer portu PostgreSQL?", klingon: "PostgreSQL joqwI' port mI'?" }, a: "5432" },
    { q: { en: "Default Redis port number?", pl: "Domyślny numer portu Redis?", klingon: "Redis nom-qeng port mI'?" }, a: "6379" },
    { q: { en: "Linux command to list directory contents?", pl: "Polecenie Linux do listowania zawartości katalogu?", klingon: "Linux Daqmey yIlegh Qu'?" }, a: "ls" },
    { q: { en: "Linux command to change file permissions?", pl: "Polecenie Linux do zmiany uprawnień pliku?", klingon: "Linux lIgh-nIS Qu' pong?" }, a: "chmod" },
    { q: { en: "Linux command to search text in files?", pl: "Polecenie Linux do wyszukiwania tekstu w plikach?", klingon: "Linux mu'mey-nej Qu'?" }, a: "grep" },
    { q: { en: "Linux command to change file ownership?", pl: "Polecenie Linux do zmiany właściciela pliku?", klingon: "Linux HoD-choH Qu' pong?" }, a: "chown" },
    { q: { en: "Linux command to show running processes?", pl: "Polecenie Linux do wyświetlania procesów?", klingon: "Linux bIQ-ta' vumwI' leghmeH Qu'?" }, a: "ps" },
    { q: { en: "Linux command for real-time process monitoring?", pl: "Polecenie Linux do monitorowania procesów w czasie rzeczywistym?", klingon: "Linux pa'logh vumwI' legh Qu'?" }, a: "top" },
    { q: { en: "Linux command to display disk usage?", pl: "Polecenie Linux do wyświetlania użycia dysku?", klingon: "Linux Doch-naQ Hap-lo' Qu'?" }, a: "df" },
    { q: { en: "Linux command to show directory space usage?", pl: "Polecenie Linux do pokazywania użycia miejsca w katalogu?", klingon: "Linux Daqmey-naw' Qu' pong?" }, a: "du" },
    { q: { en: "Linux stream editor for text transformation?", pl: "Linuxowy edytor strumieni do transformacji tekstu?", klingon: "Linux bIQ-mu' choHwI' pong?" }, a: "sed" },
    { q: { en: "Linux command for pattern scanning and processing?", pl: "Polecenie Linux do skanowania i przetwarzania wzorców?", klingon: "Linux ngech-legh je vum Qu'?" }, a: "awk" },
    { q: { en: "Linux command to find files and directories?", pl: "Polecenie Linux do znajdowania plików i katalogów?", klingon: "Linux Doch-nej Qu' pong?" }, a: "find" },
    { q: { en: "Linux command to kill a process by PID?", pl: "Polecenie Linux do zabijania procesu po PID?", klingon: "Linux vumwI' HoH Qu' pong?" }, a: "kill" },
    { q: { en: "Linux command to compress files with gzip?", pl: "Polecenie Linux do kompresji plików gzip?", klingon: "Linux Doch-toD gzip Qu'?" }, a: "gzip" },
    { q: { en: "Linux command to archive files and directories?", pl: "Polecenie Linux do archiwizacji plików?", klingon: "Linux Doch-pol Qu' pong?" }, a: "tar" },
    { q: { en: "Linux command to display file contents page by page?", pl: "Polecenie Linux do wyświetlania zawartości pliku strona po stronie?", klingon: "Linux Doch-legh chu' Qu'?" }, a: "less" },
    { q: { en: "Linux command to display the last lines of a file?", pl: "Polecenie Linux do wyświetlania ostatnich linii pliku?", klingon: "Linux Doch-QeD 'egh Qu'?" }, a: "tail" },
    { q: { en: "Linux command to display the first lines of a file?", pl: "Polecenie Linux do wyświetlania pierwszych linii pliku?", klingon: "Linux Doch-QeD wa' Qu'?" }, a: "head" },
    { q: { en: "Linux command to create a symbolic link?", pl: "Polecenie Linux do tworzenia dowiązania symbolicznego?", klingon: "Linux lop-lIngwI' Qu' pong?" }, a: "ln" },
    { q: { en: "Linux command to check network connectivity?", pl: "Polecenie Linux do sprawdzania połączenia sieciowej?", klingon: "Linux qach-latlh tlha' Qu'?" }, a: "ping" },
    { q: { en: "Linux command to count lines, words, bytes in a file?", pl: "Polecenie Linux do liczenia linii, słów, bajtów?", klingon: "Linux mI'-roS Qu' pong?" }, a: "wc" },
    { q: { en: "Git command to stage all changes?", pl: "Polecenie Git do dodawania wszystkich zmian?", klingon: "Git Hoch-choH qem Qu'?" }, a: "add" },
    { q: { en: "Git command to rewrite history interactively?", pl: "Polecenie Git do interaktywnego przepisywania historii?", klingon: "Git qun-choH vIH Qu'?" }, a: "rebase" },
    { q: { en: "Git command to temporarily save uncommitted changes?", pl: "Polecenie Git do tymczasowego zapisu niezatwierdzonych zmian?", klingon: "Git choH-pol tugh Qu'?" }, a: "stash" },
    { q: { en: "Git command to find the commit that introduced a bug?", pl: "Polecenie Git do znajdowania commita wprowadzającego błąd?", klingon: "Git Qagh-Sam bIQ Qu'?" }, a: "bisect" },
    { q: { en: "Git command to combine branches?", pl: "Polecenie Git do łączenia gałęzi?", klingon: "Git QI'tu'-boq Qu'?" }, a: "merge" },
    { q: { en: "Git command to create a new branch?", pl: "Polecenie Git do tworzenia nowej gałęzi?", klingon: "Git chu' ngem-lIngwI' Qu'?" }, a: "branch" },
    { q: { en: "Git command to download changes from remote?", pl: "Polecenie Git do pobierania zmian ze zdalnego repozytorium?", klingon: "Git Huj-choH tlhap Qu'?" }, a: "pull" },
    { q: { en: "Git command to upload changes to remote?", pl: "Polecenie Git do wysyłania zmian do zdalnego repozytorium?", klingon: "Git Huj-choH lab Qu'?" }, a: "push" },
    { q: { en: "Git command to switch branches?", pl: "Polecenie Git do przełączania gałęzi?", klingon: "Git ngem-choH Qu'?" }, a: "checkout" },
    { q: { en: "Git command to initialize a new repository?", pl: "Polecenie Git do inicjalizacji nowego repozytorium?", klingon: "Git chu' Daqmey-moH Qu'?" }, a: "init" },
    { q: { en: "Git command to clone a repository?", pl: "Polecenie Git do klonowania repozytorium?", klingon: "Git latlh-lIngwI' Qu'?" }, a: "clone" },
    { q: { en: "Git command to record staged changes?", pl: "Polecenie Git do zapisywania zaplanowanych zmian?", klingon: "Git choH-pol qun Qu'?" }, a: "commit" },
    { q: { en: "Protocol used by ping?", pl: "Protokół używany przez ping?", klingon: "Ping Qu' mIw pong?" }, a: "icmp" },
    { q: { en: "Protocol that maps IP to MAC addresses?", pl: "Protokół mapujący IP na adresy MAC?", klingon: "IP-MAC SIch mIw pong?" }, a: "arp" },
    { q: { en: "Connectionless transport protocol?", pl: "Bezpołączeniowy protokół transportowy?", klingon: "lIng-Hutlh qeng mIw pong?" }, a: "udp" },
    { q: { en: "Connection-oriented transport protocol?", pl: "Połączeniowy protokół transportowy?", klingon: "lIng-nIH qeng mIw pong?" }, a: "tcp" },
    { q: { en: "Protocol that assigns IP addresses automatically?", pl: "Protokół przypisujący adresy IP automatycznie?", klingon: "IP-mI' nob tlhaq mIw pong?" }, a: "dhcp" },
    { q: { en: "Protocol for translating domain names to IPs?", pl: "Protokół tłumaczący nazwy domen na adresy IP?", klingon: "pong-IP choH mIw pong?" }, a: "dns" },
    { q: { en: "How many bits in an IPv4 address?", pl: "Ile bitów ma adres IPv4?", klingon: "IPv4 chach mI' mI' pIm?" }, a: "32" },
    { q: { en: "How many bits in an IPv6 address?", pl: "Ile bitów ma adres IPv6?", klingon: "IPv6 chach mI' mI' pIm?" }, a: "128" },
    { q: { en: "OSI model layer where routing occurs?", pl: "Warstwa modelu OSI, w której odbywa się routing?", klingon: "OSI He-ngaS 'ay' mI'?" }, a: "3" },
    { q: { en: "Subnet mask for a /24 network in dotted decimal?", pl: "Maska podsieci dla sieci /24 w notacji dziesiętnej?", klingon: "/24 qach chach mIw pong?" }, a: "255.255.255.0" },
    { q: { en: "Loopback IP address?", pl: "Adres IP pętli zwrotnej?", klingon: "'egh-SIch IP chach pong?" }, a: "127.0.0.1" },
    { q: { en: "AWS serverless compute service?", pl: "Bezserwerowa usługa obliczeniowa AWS?", klingon: "AWS server-Hutlh vum pong?" }, a: "lambda" },
    { q: { en: "AWS object storage service?", pl: "Usługa przechowywania obiektów AWS?", klingon: "AWS Doch-pol qa' pong?" }, a: "s3" },
    { q: { en: "AWS virtual machine service?", pl: "Usługa maszyn wirtualnych AWS?", klingon: "AWS Hov-ghaH Qu' pong?" }, a: "ec2" },
    { q: { en: "AWS managed Kubernetes service?", pl: "Zarządzana usługa Kubernetes AWS?", klingon: "AWS Kubernetes HoD-nIH pong?" }, a: "eks" },
    { q: { en: "AWS managed container service (no K8s)?", pl: "Zarządzana usługa kontenerów AWS (bez K8s)?", klingon: "AWS Hap-qeq HoD pong?" }, a: "ecs" },
    { q: { en: "AWS content delivery network service?", pl: "Usługa sieci dostarczania treści AWS?", klingon: "AWS Doch-lab nom mIw pong?" }, a: "cloudfront" },
    { q: { en: "AWS DNS and routing service?", pl: "Usługa DNS i routingu AWS?", klingon: "AWS pong-SIch He-ngaS pong?" }, a: "route53" },
    { q: { en: "AWS managed relational database service?", pl: "Zarządzana relacyjna usługa bazy danych AWS?", klingon: "AWS Soj-tev HoD mIw pong?" }, a: "rds" },
    { q: { en: "AWS infrastructure-as-code service?", pl: "Usługa infrastruktury jako kodu AWS?", klingon: "AWS qach-mu' lIngwI' pong?" }, a: "cloudformation" },
    { q: { en: "AWS IAM stands for?", pl: "Co oznacza AWS IAM?", klingon: "AWS IAM mu' pong?" }, a: "iam" },
    { q: { en: "AWS notification pub/sub service?", pl: "Usługa powiadomień pub/sub AWS?", klingon: "AWS QIn-lab mIw pong?" }, a: "sns" },
    { q: { en: "AWS message queuing service?", pl: "Usługa kolejkowania wiadomości AWS?", klingon: "AWS QIn-rIn mIw pong?" }, a: "sqs" },
    { q: { en: "Dockerfile instruction to set the base image?", pl: "Instrukcja Dockerfile do ustawienia obrazu bazowego?", klingon: "Dockerfile Hov-qach wa' Qu'?" }, a: "from" },
    { q: { en: "Dockerfile instruction to execute a command during build?", pl: "Instrukcja Dockerfile do wykonywania polecenia podczas budowania?", klingon: "Dockerfile lIngwI' Qu' vum?" }, a: "run" },
    { q: { en: "Dockerfile instruction to copy files into the image?", pl: "Instrukcja Dockerfile do kopiowania plików do obrazu?", klingon: "Dockerfile Doch-latlh tlhap Qu'?" }, a: "copy" },
    { q: { en: "Dockerfile instruction to set environment variables?", pl: "Instrukcja Dockerfile do ustawiania zmiennych środowiskowych?", klingon: "Dockerfile Daqmey-mIw cher Qu'?" }, a: "env" },
    { q: { en: "Dockerfile instruction to declare exposed ports?", pl: "Instrukcja Dockerfile do deklarowania eksponowanych portów?", klingon: "Dockerfile port-legh Qu'?" }, a: "expose" },
    { q: { en: "Dockerfile instruction to specify the default command?", pl: "Instrukcja Dockerfile do określania domyślnego polecenia?", klingon: "Dockerfile wa'DIch Qu' cher?" }, a: "cmd" },
    { q: { en: "Dockerfile instruction to set the working directory?", pl: "Instrukcja Dockerfile do ustawienia katalogu roboczego?", klingon: "Dockerfile vum-Daqmey cher Qu'?" }, a: "workdir" },
    { q: { en: "Docker command to list running containers?", pl: "Polecenie Docker do listowania uruchomionych kontenerów?", klingon: "Docker Hap-qeq legh Qu'?" }, a: "ps" },
    { q: { en: "Docker command to build an image from Dockerfile?", pl: "Polecenie Docker do budowania obrazu z Dockerfile?", klingon: "Docker Hov-qach lIngwI' Qu'?" }, a: "build" },
    { q: { en: "Docker command to download an image from registry?", pl: "Polecenie Docker do pobierania obrazu z rejestru?", klingon: "Docker Hov-qach tlhap Qu'?" }, a: "pull" },
    { q: { en: "Docker command to stop a running container?", pl: "Polecenie Docker do zatrzymywania uruchomionego kontenera?", klingon: "Docker Hap-qeq mev Qu'?" }, a: "stop" },
    { q: { en: "Docker multi-container orchestration tool?", pl: "Narzędzie Docker do orkiestracji wielu kontenerów?", klingon: "Docker Hoch-Hap-qeq ra' Qu'?" }, a: "compose" },
    { q: { en: "Smallest deployable unit in Kubernetes?", pl: "Najmniejsza jednostka wdrożeniowa w Kubernetes?", klingon: "Kubernetes wa'Dich Hap-qeq pong?" }, a: "pod" },
    { q: { en: "Kubernetes package manager?", pl: "Menedżer pakietów Kubernetes?", klingon: "Kubernetes Doch-nob HoD pong?" }, a: "helm" },
    { q: { en: "Kubernetes object that maintains a set of replica pods?", pl: "Obiekt Kubernetes utrzymujący zestaw replik podów?", klingon: "Kubernetes boq-pod lIngwI' pong?" }, a: "replicaset" },
    { q: { en: "Kubernetes CLI tool?", pl: "Narzędzie CLI Kubernetes?", klingon: "Kubernetes Qu'-moH pong?" }, a: "kubectl" },
    { q: { en: "Kubernetes object to expose pods as a network service?", pl: "Obiekt Kubernetes do eksponowania podów jako usługi sieciowej?", klingon: "Kubernetes pod-legh mIw pong?" }, a: "service" },
    { q: { en: "Kubernetes object for deploying stateless applications?", pl: "Obiekt Kubernetes do wdrażania bezstanowych aplikacji?", klingon: "Kubernetes Hap-lab lIngwI' pong?" }, a: "deployment" },
    { q: { en: "Kubernetes object to store configuration data?", pl: "Obiekt Kubernetes do przechowywania danych konfiguracyjnych?", klingon: "Kubernetes mIw-Doch pol pong?" }, a: "configmap" },
    { q: { en: "Kubernetes object to store sensitive data?", pl: "Obiekt Kubernetes do przechowywania poufnych danych?", klingon: "Kubernetes QaD-Doch pol pong?" }, a: "secret" },
    { q: { en: "Kubernetes worker machine?", pl: "Maszyna robocza Kubernetes?", klingon: "Kubernetes vumwI' Hov pong?" }, a: "node" },
    { q: { en: "Kubernetes ingress controller popularly used?", pl: "Popularny kontroler wejścia Kubernetes?", klingon: "Kubernetes DaH-lIng naw' pong?" }, a: "nginx" },
    { q: { en: "Kubernetes object that runs a pod on every node?", pl: "Obiekt Kubernetes uruchamiający pod na każdym węźle?", klingon: "Kubernetes Hoch-node pod Qu'?" }, a: "daemonset" },
    { q: { en: "Kubernetes horizontal auto-scaling object abbreviation?", pl: "Skrót obiektu automatycznego skalowania poziomego Kubernetes?", klingon: "Kubernetes SaS-nab mIw pong?" }, a: "hpa" },
    { q: { en: "Popular open-source CI/CD automation server?", pl: "Popularny open-source serwer automatyzacji CI/CD?", klingon: "Hoch-vum CI/CD ra'wI' pong?" }, a: "jenkins" },
    { q: { en: "Infrastructure as code tool by HashiCorp?", pl: "Narzędzie infrastruktury jako kodu od HashiCorp?", klingon: "HashiCorp qach-mu' Qu' pong?" }, a: "terraform" },
    { q: { en: "Configuration management tool using YAML playbooks?", pl: "Narzędzie do zarządzania konfiguracją używające playbooków YAML?", klingon: "YAML mIw-HoD ra' Qu' pong?" }, a: "ansible" },
    { q: { en: "Terraform command to apply infrastructure changes?", pl: "Polecenie Terraform do stosowania zmian infrastruktury?", klingon: "Terraform qach-choH vum Qu'?" }, a: "apply" },
    { q: { en: "Terraform command to preview changes?", pl: "Polecenie Terraform do podglądu zmian?", klingon: "Terraform choH-legh tugh Qu'?" }, a: "plan" },
    { q: { en: "Terraform state file extension?", pl: "Rozszerzenie pliku stanu Terraform?", klingon: "Terraform ta'-Doch pong?" }, a: "tfstate" },
    { q: { en: "GitLab CI configuration file name?", pl: "Nazwa pliku konfiguracyjnego GitLab CI?", klingon: "GitLab CI mIw-Doch pong?" }, a: ".gitlab-ci.yml" },
    { q: { en: "GitHub Actions workflow directory?", pl: "Katalog workflow GitHub Actions?", klingon: "GitHub Actions Daqmey pong?" }, a: ".github" },
    { q: { en: "Popular container registry by Docker?", pl: "Popularny rejestr kontenerów od Docker?", klingon: "Docker Hov-qach pol Daqmey?" }, a: "dockerhub" },
    { q: { en: "HashiCorp secrets management tool?", pl: "Narzędzie do zarządzania sekretami HashiCorp?", klingon: "HashiCorp QaD-Doch HoD pong?" }, a: "vault" },
    { q: { en: "Popular metrics visualization dashboard tool?", pl: "Popularne narzędzie do wizualizacji metryk?", klingon: "Doch-ngaS legh-nab Qu' pong?" }, a: "grafana" },
    { q: { en: "Popular log aggregation stack: Elasticsearch Logstash ___?", pl: "Popularny stos agregacji logów: Elasticsearch Logstash ___?", klingon: "ELK QeD-boq rIn Doch pong?" }, a: "kibana" },
    { q: { en: "Python package installer?", pl: "Instalator pakietów Python?", klingon: "Python Doch-nob lIngwI' pong?" }, a: "pip" },
    { q: { en: "Python web framework for large applications?", pl: "Framework webowy Python dla dużych aplikacji?", klingon: "Python Doj-qach nab pong?" }, a: "django" },
    { q: { en: "Python lightweight web framework?", pl: "Lekki framework webowy Python?", klingon: "Python nom-qach nab pong?" }, a: "flask" },
    { q: { en: "Python virtual environment creation tool?", pl: "Narzędzie Python do tworzenia wirtualnych środowisk?", klingon: "Python Hov-Daqmey lIngwI' pong?" }, a: "venv" },
    { q: { en: "Python file extension?", pl: "Rozszerzenie pliku Python?", klingon: "Python Doch mIw pong?" }, a: "py" },
    { q: { en: "Python WSGI HTTP server for production?", pl: "Serwer HTTP Python WSGI do produkcji?", klingon: "Python vum-qach ra'wI' pong?" }, a: "gunicorn" },
    { q: { en: "Python testing framework?", pl: "Framework do testowania Python?", klingon: "Python Qagh-Sam Qu' pong?" }, a: "pytest" },
    { q: { en: "Python async web framework?", pl: "Asynchroniczny framework webowy Python?", klingon: "Python nom-vum qach nab pong?" }, a: "fastapi" },
    { q: { en: "Python code formatter?", pl: "Formatownik kodu Python?", klingon: "Python mu'-choH Qu' pong?" }, a: "black" },
    { q: { en: "Python dependency file name convention?", pl: "Konwencja nazwy pliku zależności Python?", klingon: "Python Hoch-nIH Doch pong?" }, a: "requirements.txt" },
    { q: { en: "Python built-in HTTP server module (Python 3)?", pl: "Wbudowany moduł serwera HTTP Python 3?", klingon: "Python 3 ra'wI' mIw pong?" }, a: "http.server" },
    { q: { en: "Python AWS SDK library name?", pl: "Nazwa biblioteki SDK Python dla AWS?", klingon: "Python AWS Qu'-nab pong?" }, a: "boto3" },
    { q: { en: "Cross-site scripting attack abbreviation?", pl: "Skrót ataku cross-site scripting?", klingon: "qach-latlh mu'-HoH Qagh pong?" }, a: "xss" },
    { q: { en: "Cross-site request forgery abbreviation?", pl: "Skrót fałszowania żądań między witrynami?", klingon: "qach-latlh Qu'-maq pong?" }, a: "csrf" },
    { q: { en: "JSON Web Token abbreviation?", pl: "Skrót JSON Web Token?", klingon: "JSON qach-nab pong?" }, a: "jwt" },
    { q: { en: "Open authorization framework?", pl: "Otwarty framework autoryzacji?", klingon: "Hoch-chaw' mIw pong?" }, a: "oauth" },
    { q: { en: "SQL injection target?", pl: "Cel ataku SQL injection?", klingon: "SQL Qagh-maq Doch pong?" }, a: "database" },
    { q: { en: "Hash algorithm producing 256-bit digest?", pl: "Algorytm haszujący produkujący 256-bitowy skrót?", klingon: "256-mI' Doch-choH mIw pong?" }, a: "sha256" },
    { q: { en: "Security framework: principle of least ___?", pl: "Zasada bezpieczeństwa: zasada najmniejszych ___?", klingon: "QaD mIw: wa'Dich nIvqu' ___?" }, a: "privilege" },
    { q: { en: "Tool to scan for open ports?", pl: "Narzędzie do skanowania otwartych portów?", klingon: "port-Hoch Sam Qu' pong?" }, a: "nmap" },
    { q: { en: "Certificate format extension for public key certificates?", pl: "Rozszerzenie formatu certyfikatu klucza publicznego?", klingon: "Hoch-nab Doch mIw pong?" }, a: "pem" },
    { q: { en: "Man-in-the-middle attack abbreviation?", pl: "Skrót ataku man-in-the-middle?", klingon: "Dung-HoH Qagh pong?" }, a: "mitm" },
    { q: { en: "Open-source firewall management tool on Linux?", pl: "Narzędzie do zarządzania zaporą ogniową na Linuksie?", klingon: "Linux ngab-lIng HoD Qu' pong?" }, a: "iptables" },
    { q: { en: "Zero-day vulnerability means the patch exists for ___ days?", pl: "Podatność zero-day oznacza, że łatka istnieje przez ___ dni?", klingon: "zero-day Qagh mIw pong?" }, a: "0" },
    { q: { en: "Data format using key-value pairs, often used in APIs?", pl: "Format danych z parami klucz-wartość, często używany w API?", klingon: "nIH-vInDa' Doch-mIw pong?" }, a: "json" },
    { q: { en: "REST HTTP method to create a resource?", pl: "Metoda HTTP REST do tworzenia zasobu?", klingon: "REST Doch-lIngwI' Qu' pong?" }, a: "post" },
    { q: { en: "REST HTTP method to update a resource entirely?", pl: "Metoda HTTP REST do pełnej aktualizacji zasobu?", klingon: "REST Doch-choH Hoch Qu' pong?" }, a: "put" },
    { q: { en: "REST HTTP method to read a resource?", pl: "Metoda HTTP REST do odczytu zasobu?", klingon: "REST Doch-legh Qu' pong?" }, a: "get" },
    { q: { en: "REST HTTP method to delete a resource?", pl: "Metoda HTTP REST do usuwania zasobu?", klingon: "REST Doch-HoH Qu' pong?" }, a: "delete" },
    { q: { en: "HTTP status code for Not Found?", pl: "Kod statusu HTTP dla Nie Znaleziono?", klingon: "HTTP Doch-Hutlh mI' pong?" }, a: "404" },
    { q: { en: "HTTP status code for Internal Server Error?", pl: "Kod statusu HTTP dla Błędu Wewnętrznego Serwera?", klingon: "HTTP ra'wI' Qagh mI' pong?" }, a: "500" },
    { q: { en: "HTTP status code for OK?", pl: "Kod statusu HTTP dla OK?", klingon: "HTTP majQa' mI' pong?" }, a: "200" },
    { q: { en: "HTTP status code for Created?", pl: "Kod statusu HTTP dla Utworzono?", klingon: "HTTP lIngwI' mI' pong?" }, a: "201" },
    { q: { en: "HTTP status code for Unauthorized?", pl: "Kod statusu HTTP dla Nieautoryzowany?", klingon: "HTTP chaw'-Hutlh mI' pong?" }, a: "401" },
    { q: { en: "HTTP status code for Forbidden?", pl: "Kod statusu HTTP dla Zabroniony?", klingon: "HTTP qama' mI' pong?" }, a: "403" },
    { q: { en: "CAP theorem: the C stands for?", pl: "Twierdzenie CAP: C oznacza?", klingon: "CAP DI' C mIw pong?" }, a: "consistency" },
    { q: { en: "Linux signal number for SIGKILL?", pl: "Numer sygnału Linux dla SIGKILL?", klingon: "Linux SIGKILL mI' pong?" }, a: "9" },
    { q: { en: "Linux signal number for SIGTERM?", pl: "Numer sygnału Linux dla SIGTERM?", klingon: "Linux SIGTERM mI' pong?" }, a: "15" },
    { q: { en: "Default shell in most Linux distributions?", pl: "Domyślna powłoka w większości dystrybucji Linuksa?", klingon: "Linux mu'-ngem wa'Dich pong?" }, a: "bash" },
    { q: { en: "Linux process ID of the init/systemd process?", pl: "ID procesu init/systemd w Linuksie?", klingon: "Linux wa'Dich vumwI' mI' pong?" }, a: "1" },
    { q: { en: "Tool to manage Linux services (modern)?", pl: "Narzędzie do zarządzania usługami Linuksa (nowoczesne)?", klingon: "Linux Qu'-HoD ra' Qu' pong?" }, a: "systemctl" },
    { q: { en: "Git default branch name (modern default)?", pl: "Domyślna nazwa gałęzi Git (nowoczesna domyślna)?", klingon: "Git wa'Dich ngem pong?" }, a: "main" },
    { q: { en: "Docker network driver for containers on the same host?", pl: "Sterownik sieci Docker dla kontenerów na tym samym hoście?", klingon: "Docker qach-boq mIw pong?" }, a: "bridge" },
    { q: { en: "Container runtime used by Kubernetes (modern default)?", pl: "Środowisko uruchomieniowe kontenerów używane przez Kubernetes (nowoczesne)?", klingon: "Kubernetes Hap-qeq vum mIw pong?" }, a: "containerd" },
    { q: { en: "Linux command to display network interfaces?", pl: "Polecenie Linux do wyświetlania interfejsów sieciowych?", klingon: "Linux bIQ-jIH legh Qu' pong?" }, a: "ifconfig" },
    { q: { en: "Number of octets in a MAC address?", pl: "Liczba oktetów w adresie MAC?", klingon: "MAC chach 'ay' mI' pong?" }, a: "6" },
    { q: { en: "DevOps practice of deploying many small changes frequently?", pl: "Praktyka DevOps polegająca na częstym wdrażaniu małych zmian?", klingon: "DevOps nom-lab mIw pong?" }, a: "ci" },
    { q: { en: "Kubernetes object that provides external access to services?", pl: "Obiekt Kubernetes zapewniający zewnętrzny dostęp do usług?", klingon: "Kubernetes Huj-lIng Qu' pong?" }, a: "ingress" },
    { q: { en: "Time unit in cron: * * * * * - how many fields?", pl: "Jednostka czasu w cronie: * * * * * - ile pól?", klingon: "cron Hoch mIw mI' pong?" }, a: "5" }
];
